version: '3.8'
services:
  db:
    image: postgres:13
    container_name: gutenberg_db
    
    environment:
      - POSTGRES_USER=gutenberg
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gutenberg_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: